AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cves-processing

  Sample SAM Template for cves-processing

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: cve-processor
      CodeUri: processing/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        BucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: CvesBucket
            Events: s3:ObjectCreated:*
    Connectors:
      BucketConnector:
        Properties:
          Destination:
            Id: CvesBucket
          Permissions:
            - Read
      DynamoConnector:
        Properties:
          Destination:
            Id: CvesTable
          Permissions:
            - Write
  CvesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cves-source-data
  CvesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: cves-db
      PrimaryKey:
        Name: cve_id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5